version: '3.3'
services:
    oasis:
        container_name: oasis
        volumes:
            - '/docker/oasis/data:/opt/oasis/data'
            - '/docker/oasis/storage:/media/myUSB'
        ports:
            - '8000:8000'
        image: machengim/oasis
